#!/usr/bin/env python
# -*- coding: utf-8 -*-

new_string = " "
frase = input("Digite uma frase: ")

print("Voce digitou: {}".format(frase))
for palavra in frase.split(" "):
    new_string += (palavra[::-1]+" ")
print("A frase que voce digitou invertida fica: {}".format(new_string))
