#!/usr/bin/env python
# -*- coding: utf-8 -*-
import math

a = int (input ())
b = int (input ())
c = int (input ())

if a > (b + c) | b > (a + c) | c > (a + b):
    print ("Não é possível formar um triângulo!")

else:
    p = (a+b+c)/2
    area = (p*(p-a)*(p-b)*(p-c)) ** 0.5

    print "A área é igual a: ",area
